### ISSUE TITLE
Strict mode from outside breaks script

### ISSUE THREAD

**Issue by chenasraf** [mojs/mojs#126] opened 2017-03-15 16:18 UTC
In our gulp task setup, we take vendor JS files, concat & minify them.

Other packages might include `'use strict';` on the top level, causing strict mode to propagate downward into functions. 

In `build/mo.js:7219`, we have this:

```js
BezierEasing.prototype.generate = function(mX1, mY1, mX2,  mY2) {
  // ...
  float32ArraySupported = indexOf.call(global, 'Float32Array') >= 0;
```
Which raises an exception when in the web page:

```
Uncaught TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (<anonymous>)
    at t.generate (vendor-f37e19184d.js:24316)
    at Function.i (vendor-f37e19184d.js:24315)
    at vendor-f37e19184d.js:24315
    at Object.e.__esModule (vendor-f37e19184d.js:24315)
    at e (vendor-f37e19184d.js:24312)
    at Object.t.__esModule.default (vendor-f37e19184d.js:24312)
    at e (vendor-f37e19184d.js:24312)
    at Object.t.__esModule.default (vendor-f37e19184d.js:24313)
    at e (vendor-f37e19184d.js:24312)
```

Adding a null check before it fixes this bug:

```js
  float32ArraySupported = global != null && indexOf.call(global, 'Float32Array') >= 0;
```

However, I'm not sure if falling to `false` would be the best option here, as I'm not sure what this line means in the longer run.

Thought this should be checked out. In my case I removed any/all strict definitions from the result.

**Comment by legomushroom** [comment] 2017-03-15 19:01
Hey @chenasraf, thanks for the heads up!

Do you think that's the only problem or there could be more pitfalls like that?

**Comment by chenasraf** [comment] 2017-03-16 08:16
Some of the code already uses strict mode (from what I've seen), and nothing else broke once I fixed that one line, so I don't think there's much else to do other than decide how to treat the case with a null `global` var. You might as well use strict mode on the whole file and make sure the code is compatible with it at its entirety.

**Comment by legomushroom** [comment] 2017-03-16 18:27
@chenasraf thanks for the info, it should be an easy fix. I started work toward `mojs@2` and there is `strict mode` enabled by default.

**Comment by kknopper** [comment] 2017-05-18 06:58
@legomushroom 
I'm using a gulp-webpack setup for my project using es6 imports and am running into this same error:

`Uncaught TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (<anonymous>)
    at BezierEasing.generate (main.js:20772)
    at Function.wrapper (main.js:17894)
    at main.js:19045
    at Object.exports.__esModule (main.js:19301)
    at __webpack_require__ (main.js:11092)
    at Object.exports.__esModule (main.js:13729)
    at __webpack_require__ (main.js:11092)
    at Object.exports.__esModule (main.js:15580)
    at __webpack_require__ (main.js:11092)`

not quite sure if this is being caused by the strict propagation described above or not.
I've tried using mojs version 0.265.9 as described in issue 50, but I've still been getting the same error. 
[https://github.com/legomushroom/mojs/issues/50](url)

is there a quick fix for this?

**Comment by chenasraf** [comment] 2017-05-18 07:29
@kknopper In my case I worked around this by removing any usages of `'use strict'` using [gulp-string-replace](https://github.com/tomaszczechowski/gulp-string-replace), like so:

```bash
npm i --save-dev gulp-string-replace
```

```javascript
var replace = require('gulp-string-replace');
gulp.task(..., function() {
  return ...
    .pipe(replace(/["']*use strict["';]*/gi, ''))
})
```

**Comment by kknopper** [comment] 2017-05-18 08:42
@chenasraf 
This worked for me, thank you!

**Comment by BertrandGouny** [comment] 2019-07-24 21:07
this is still an issue :(

**Comment by xavierfoucrier** [comment] 2019-07-30 16:03
Hi @BertrandGouny,

Sorry for the late reply, for now we have not planned to work on strict mode inside the current build as we are a little busy with @Sandstedt on other private projects.

Be sure we will inform you of the situation when it will move forward :wink:
Thanks for your interest for `mojs`.

**Comment by BertrandGouny** [comment] 2019-08-01 18:40
@xavierfoucrier thanks :)

**Comment by FateRiddle** [comment] 2019-11-06 07:33
This is still an issue. @xavierfoucrier And the first work around provided isn't working. I'm not planning on using gulp in my project so I can't test the second one. I really like this project, can we get this one fixed?

**Comment by xavierfoucrier** [comment] 2019-11-06 13:41
Hi @FateRiddle,

Sorry but I haven't much time to work on that shortly... but will consider dinging inside and investigating further as soon as possible.

Thanks for your patience.

**Comment by thirschel** [comment] 2020-02-09 21:44
@xavierfoucrier I have created PR (#224) as a fix for this issue.

**Closed** 2021-03-24 23:23 UTC
Labels: bug, core
