### ISSUE TITLE
Not Compatible issue with Angular 2

### ISSUE THREAD

**Issue by ruucm-working** [mojs/mojs#149] opened 2017-07-24 01:40 UTC
Angular 2 's ngIf & ngFor doesn't compatible with the mo.js lib.

When I add mo.js to my project, there's no error log on console and animation works great, but Angular 2 features not going to very well.

I've just added using <script> like this code
```html
<body>
	<harbor-app></harbor-app>
	<script src="/mojs/mo.js"></script>
</body>
```

**Comment by legomushroom** [comment] 2017-07-25 03:46
Hey @ruucm!

Thanks for the issue! Could you provide me with more info regarding what does wrong with Angular, and what features look off fo you?

Thanks a lot!

**Comment by wolfhoundjesse** [comment] 2017-08-03 19:13
Where are the tags for your app? Are you trying to have bundled and unbundled code working together?

**Comment by cswarb** [comment] 2017-09-09 22:46
@legomushroom 

One of the main issues I am finding so far is that data binding breaks when getting data over http after importing the library (Just placing a link to it in index page). 

Where I have implemented a resolver on a route to get data, it fires and the promise is resolved. However, the data is never bound to the view inside a component. As @ruucm said, no errors show Angular side.

For reference I am using the latest Angular version (4.2+).

**Comment by lindsaymacvean** [comment] 2018-11-19 01:13
Any news on this. I think I am running into the same issues.

**Comment by xavierfoucrier** [comment] 2021-03-03 15:23
Hi everyone!

As there is no more code explanation here and the issue is pretty old, I am closing it.
The latest `@mojs/core` version **works fine with React**, so I guess it's the same with latest Angular version.

Have a look at our **dedicated SSR section** on the documentation website:
https://mojs.github.io/tutorials/usage-with-react.html.

> Note that documentation will evolve and contain many other framework implementations in the future.

**Closed by xavierfoucrier** 2021-03-03 15:23 UTC
Labels: bug
