### ISSUE TITLE
Changing shape of object

### ISSUE THREAD

**Issue by y-sumanth** [mojs/mojs#222] opened 2019-11-16 03:38 UTC
I know there is no way to change the shape of object now. But this will be very useful add-on of the library. Can the contributors please consider this? Like..
```
new mojs.Shape({
    shape: 'circle'
}).then({
    shape: 'rect'
})
```

Or please suggest any possible way to achieve this. Thanks.

**Comment by xavierfoucrier** [comment] 2019-11-16 22:05
Hi @y-sumanth,

What you are talking about is literally **SVG morphing**, this is already a feature request made a long time ago :wink: 

Today, some other libraries similar to `mojs` are using specific modules to do that, like the famous **Polymorph** library that is very easy to use: https://notoriousb1t.github.io/polymorph-docs.

I will mark your issue as duplicate of #67.
Thanks for your interest in `mojs` :v:

**Closed by xavierfoucrier** 2019-11-16 22:05 UTC
Labels: duplicate
